language: ruby

script:
  - "bundle exec rspec spec"

bundler_args: --without development debug

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database basecampapp_database_test;' -U postgres