language: ruby

script:
  - "bundle exec rspec spec"

bundler_args: --without development debug

before_script:
  - psql -c 'create database basecampapp_database_test;' -U postgres
  - rake db:migrate RAILS_ENV=test
